version: '3'

services:
  be:
    container_name: 'flask-be'
    image: 'flask-be'
    build:
      context: flask-be/
    ports:
      - "5000:5000"
    # networks:
    #   - my-api.dev
  fe:
    container_name: 'react-fe'
    image: 'react-fe'
    build:
      context: react-fe/
    ports:
      - "3000:3000"
    # networks:
    #   - my-api.dev
    # links:
    #   - be

# networks:
#   my-api.dev: