openapi: 3.0.0
info:
  title: "FLASK REST API"
  description: "api for cloudy app"
  version: "0.0.1"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
        money:
          type: "string"
  parameters:
    name:
      name: "name"
      description: "name of person"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /people:
    get:
      operationId: "handler.read_all"
      tags:
        - "people"
      summary: "Read list of all people"
      responses:
        "200":
          description: "Successful read of pople list"
    post:
      operationId: "handler.create"
      tags:
        - "people"
      summary: "Create a person"
      requestBody:
        description: "Person to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"   ## refer to var defined in components block
      responses:
        "201":
          description: "Successful creation of new person"
  /people/{name}:
    get:
      operationId: "handler.read_one"
      tags:
        - People
      summary: "Read one person"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successful read of one person"
    put:
      tags:
        - People
      operationId: "handler.update"
      summary: "Update a axisting person"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully updated person"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
    delete:
      tags:
        - People
      operationId: "handler.delete"
      summary: "Delete person"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "204":
          description: "Successfully deleted person"