apiVersion: v1
kind: Service
metadata:
  name: svc-fe
  namespace: dev
  labels:
    kubernetes.io/service-name: svc-fe
spec:
  # type: NodePort
  selector:
    app: react-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30007